USE swiggy;
SELECT * FROM restaurants;
-- 1. Which restaurant of abohar is visited by least number of people?
SELECT  name,city,rating_count AS Least_no FROM restaurants
WHERE city='abohar' AND
rating_count=(SELECT  MIN(rating_count) FROM restaurants WHERE city='abohar');





-- 2. Which restaurant has generated maximum revenue all over india?
SELECT name, cost*rating_count AS revenue
FROM restaurants
WHERE cost*rating_count =(SELECT MAX(cost*rating_count) FROM restaurants);

-- CTE (COMMON TABLE EXPRESSION)
WITH t1 AS(SELECT name, cost*rating_count AS revenue
FROM restaurants)
SELECT name, revenue
FROM t1
WHERE revenue=(SELECT MAX(revenue) FROM t1);

-- 3. How many restaurants are having rating more than the average rating?
SELECT COUNT(*)  AS better_rest FROM restaurants
WHERE rating>(SELECT AVG(rating) FROM restaurants);


-- 4. Which restaurant of Delhi has generated most revenue?
WITH t1 AS (SELECT name,city,cost*rating_count AS revenue
FROM restaurants
WHERE city='Delhi' ) 
SELECT name , revenue FROM t1
WHERE revenue=(SELECT MAX(revenue) FROM t1);


-- 5. Which restaurant chain has maximum number of restaurants?
SELECT name, COUNT(*) AS name_of_outlets
FROM restaurants
GROUP BY name
ORDER BY COUNT(*) DESC
LIMIT 5;


-- 6. Which restaurant chain has generated maximum revenue?
WITH t1 AS (SELECT name, SUM(cost*rating_count) AS revenue
FROM restaurants
GROUP BY name )
SELECT name,revenue 
FROM t1
WHERE revenue=(SELECT MAX(revenue) FROM t1);




-- 7. Which city has maximum number of restaurants?
SELECT city,COUNT(*) FROM restaurants
GROUP BY city
ORDER BY COUNT(*) DESC
LIMIT 1;

-- 8. Which city has generated maximum revenue all over india?

WITH t1 AS (SELECT city, SUM(cost*rating_count) AS revenue
FROM restaurants
GROUP BY city )
SELECT city,revenue 
FROM t1
WHERE revenue=(SELECT MAX(revenue) FROM t1);
-- 9. List 10 least expensive cuisines?
SELECT cuisine, AVG(cost) AS avg_cost
FROM restaurants
GROUP BY cuisine
ORDER BY avg_cost ASC
LIMIT 10;


-- 10. List 10 most expensive cuisines?
SELECT cuisine, AVG(cost) AS avg_cost
FROM restaurants
GROUP BY cuisine
ORDER BY avg_cost DESC
LIMIT 10;


-- 11. What is the city is having Biryani as most popular cuisine
SELECT city,SUM(rating_count) AS biryani_fav
FROM restaurants
WHERE cuisine='Biryani'
GROUP BY city
ORDER BY biryani_fav DESC
LIMIT 1;

-- 12. List top 10 unique restaurants with unique name only throughout the dataset as per generate maximum revenue (Single restaurant with that name)
SELECT DISTINCT(name),SUM(cost*rating_count) AS revenue
FROM restaurants
GROUP BY name
HAVING COUNT(*) =1
ORDER BY revenue DESC
LIMIT 10;

-- Window Function


-- 13. SELECT all records from the restaurants table.
SELECT * FROM  restaurants;

-- 14. Rank every restaurant from most expensive to least expensive.
SELECT *,RANK()
OVER(ORDER BY cost DESC) AS rank1
FROM restaurants;

-- 15. Rank every restaurant from most visited to least visited.
SELECT * ,RANK()
OVER(ORDER BY rating_count DESC) AS visited
FROM restaurants;


-- 16. Rank every restaurant from most expensive to least expensive as per their city.
SELECT *, RANK()
OVER(PARTITION BY city ORDER BY cost DESC) AS ranking
FROM restaurants;

-- 17. Dense-rank every restaurant from most expensive to least expensive as per their city.
SELECT *,DENSE_RANK()
OVER(PARTITION BY city ORDER BY cost DESC) AS ranking
FROM restaurants;

-- 18. Row-number every restaurant from most expensive to least expensive as per their city.
SELECT *,ROW_NUMBER()
OVER(PARTITION BY city ORDER BY cost DESC) AS numbering
FROM restaurants;

-- Give restaurant with good and bad rating where rating > 4 is good
SELECT name,rating,IF(rating>4,"good" ,"bad") AS label From restaurants;


-- 19. Rank the restaurant based on their prices (most to least expensive) 
        --   as per cuisine using rank, dense_rank, and row_number.
        SELECT *,RANK() 
        OVER(PARTITION BY cuisine ORDER BY cost DESC) AS rank_r,
		DENSE_RANK() 
		OVER(PARTITION BY cuisine ORDER BY cost DESC) AS de_rank,
        ROW_NUMBER()
		OVER(PARTITION BY cuisine ORDER BY cost DESC) AS row_num
        FROM restaurants;
-- 20. Find top 5 restaurants of every city as per their revenue.
WITH t1 AS (SELECT city, name,cost*rating_count AS revenue,DENSE_RANK()
 OVER(PARTITION BY city ORDER BY cost*rating_count DESC) AS top
 FROM restaurants)
 SELECT city,name,revenue,top
 FROM t1
 WHERE top<=5
 ORDER BY city,top,revenue DESC;

-- 21. Find top 5 restaurants of every cuisine as per their revenue.
WITH t1 AS(SELECT name,cuisine,cost*rating_count AS revenue, DENSE_RANK()
OVER(PARTITION BY cuisine ORDER BY cost*rating DESC) AS top
FROM restaurants)
SELECT name,cuisine,revenue,top
FROM t1
WHERE top<=5
ORDER BY cuisine,top,revenue;


-- 22. List the top 5 cuisines as per the revenue generated by top 5 restaurants of every cuisine.
WITH t1 AS (
    SELECT 
        name,
        cuisine,
        (cost * rating_count) AS revenue,
        DENSE_RANK() OVER (
            PARTITION BY cuisine 
            ORDER BY (cost * rating_count) DESC
        ) AS top
    FROM restaurants
),
t2 AS (
    SELECT  
        cuisine,
        SUM(revenue) AS total_revenue
    FROM t1
    WHERE top <= 5
    GROUP BY cuisine
),t3 AS( SELECT
    cuisine,
    total_revenue,
    DENSE_RANK() OVER (ORDER BY total_revenue DESC) AS cuisine_rank
FROM t2)
SELECT
    cuisine,
    total_revenue,cuisine_rank
FROM t3
WHERE cuisine_rank <= 5
ORDER BY cuisine_rank;

-- 23. List the top 5 cities as per the revenue generated by top 5 restaurants of every city.
WITH t1 As(SELECT name,city,cost*rating_count AS revenue  ,RANK()
OVER(PARTITION BY CITY ORDER BY cost*rating_count DESC ) AS top
FROM restaurants),
t2 AS (SELECT city,SUM(revenue) AS total_revenue
FROM t1
WHERE top<=5
GROUP BY city),
t3 AS ( SELECT city,total_revenue,RANK()
OVER(ORDER BY total_revenue DESC) AS rnk
FROM t2)
SELECT city,total_revenue 
FROM t3
WHERE rnk<=5
ORDER BY total_revenue;

-- 24. Find the total revenue generated by top 1% restaurants.
WITH t1 AS (
    SELECT 
        name,
        city,
        (cost * rating_count) AS revenue,RANK()
		OVER (ORDER BY (cost * rating_count) DESC) AS rnk
    FROM restaurants
),
total_count AS (
    SELECT COUNT(*) AS cnt FROM restaurants
),
top1perc AS (
    SELECT 
        t1.name,
        t1.revenue
    FROM t1
    CROSS JOIN total_count c
    WHERE t1.rnk <= CEIL(c.cnt * 0.01)
)
SELECT SUM(revenue) AS total_top1
FROM top1perc;


-- 25. Find the total revenue generated by top 20% restaurants.
WITH  ranked AS(SELECT  name,city,cost*rating_count AS revenue,RANK()
OVER (ORDER BY (cost * rating_count) DESC) AS rnk
FROM restaurants),
topperc AS (SELECT COUNT(*) AS cnt FROM restaurants),
top20perc AS (SELECT r.name,r.revenue
FROM ranked r
CROSS JOIN topperc t
WHERE r.rnk<=CEIL(t.cnt*0.2))
SELECT SUM(revenue) as total
FROM top20perc;


-- 26. What percentage of total revenue is generated by top 20% restaurants?
WITH ranked AS (SELECT name,city,cost*rating_count AS revenue ,ROW_NUMBER()
OVER(ORDER BY cost*rating_count DESC) AS rnk
FROM restaurants),
total_count AS(SELECT COUNT(*) AS cnt FROM restaurants),
top20perc AS( SELECT r.name,r.revenue
FROM ranked r
CROSS JOIN total_count t
WHERE r.rnk <=CEIL(t.cnt*0.2)),
total AS( SELECT SUM(cost*rating_count) AS grandtotal FROM restaurants)
SELECT 
     (SELECT SUM(revenue) FROM top20perc) AS top20rev ,total.grandtotal,
     (SELECT SUM(revenue) FROM top20perc)/total.grandtotal *100 AS percof20rev
FROM top20perc,total;